export interface ExportData {
  userProfile: {
    fitnessLevel: string
    goal: string
    equipment: string
    weeklyDays: number
    limitations: string[]
  }
  routine: {
    day: number
    title: string
    isRestDay: boolean
    exercises?: Array<{
      name: string
      instructions: string
      sets?: string
      duration?: string
      modification?: string
    }>
    description?: string
  }[]
  completedDays: number[]
  generatedDate: string
}

export function exportToText(data: ExportData): string {
  const { userProfile, routine, completedDays, generatedDate } = data
  
  let text = '='.repeat(60) + '\n'
  text += '                    FITPATH WORKOUT PLAN\n'
  text += '='.repeat(60) + '\n\n'
  
  // Header Information
  text += '📋 PROFILE INFORMATION\n'
  text += '-'.repeat(30) + '\n'
  text += `Fitness Level: ${userProfile.fitnessLevel.toUpperCase()}\n`
  text += `Primary Goal: ${userProfile.goal.replace('-', ' ').toUpperCase()}\n`
  text += `Available Equipment: ${userProfile.equipment.replace('-', ' ').toUpperCase()}\n`
  text += `Weekly Commitment: ${userProfile.weeklyDays} days\n`
  text += `Physical Limitations: ${userProfile.limitations.length > 0 ? userProfile.limitations.join(', ').toUpperCase() : 'NONE'}\n`
  text += `Generated Date: ${new Date(generatedDate).toLocaleDateString()}\n\n`
  
  // Progress Overview
  text += '📊 PROGRESS OVERVIEW\n'
  text += '-'.repeat(30) + '\n'
  text += `Completed Days: ${completedDays.length} / 7\n`
  text += `Completion Rate: ${Math.round((completedDays.length / 7) * 100)}%\n\n`
  
  // 7-Day Routine
  text += '📅 7-DAY WORKOUT ROUTINE\n'
  text += '='.repeat(60) + '\n\n'
  
  routine.forEach((day, index) => {
    const isCompleted = completedDays.includes(index)
    const status = isCompleted ? '✅ COMPLETED' : '⏳ PENDING'
    
    text += `${'='.repeat(20)} DAY ${day.day + 1} ${'='.repeat(20)}\n`
    text += `Status: ${status}\n`
    text += `Title: ${day.title}\n`
    
    if (day.isRestDay) {
      text += `Type: REST & RECOVERY\n`
      text += `Description: ${day.description}\n`
    } else {
      text += `Type: WORKOUT DAY\n`
      text += `Exercises: ${day.exercises?.length || 0} exercises\n\n`
      
      if (day.exercises) {
        day.exercises.forEach((exercise, exIndex) => {
          text += `  ${exIndex + 1}. ${exercise.name.toUpperCase()}\n`
          text += `     Instructions: ${exercise.instructions}\n`
          if (exercise.sets) text += `     Sets: ${exercise.sets}\n`
          if (exercise.duration) text += `     Duration: ${exercise.duration}\n`
          if (exercise.modification) {
            text += `     ⚠️  Modification: ${exercise.modification}\n`
          }
          text += '\n'
        })
      }
    }
    text += '\n'
  })
  
  // Footer
  text += '='.repeat(60) + '\n'
  text += '                    STAY CONSISTENT! 💪\n'
  text += '                YOUR FITNESS JOURNEY MATTERS\n'
  text += '='.repeat(60) + '\n'
  text += '\nGenerated by FitPath - Your Personal Fitness Companion\n'
  text += 'Visit us again for updated routines and progress tracking!\n'
  
  return text
}

export function exportToCSV(data: ExportData): string {
  const { routine, completedDays } = data
  
  let csv = 'Day,Title,Type,Status,Exercise Count,Notes\n'
  
  routine.forEach((day, index) => {
    const isCompleted = completedDays.includes(index)
    const status = isCompleted ? 'Completed' : 'Pending'
    const type = day.isRestDay ? 'Rest Day' : 'Workout'
    const exerciseCount = day.isRestDay ? 0 : day.exercises?.length || 0
    const notes = day.isRestDay ? day.description || '' : `${exerciseCount} exercises scheduled`
    
    csv += `${day.day + 1},"${day.title}",${type},${status},${exerciseCount},"${notes}"\n`
  })
  
  return csv
}

export function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

export function exportWorkoutPlan(data: ExportData, format: 'text' | 'csv') {
  const timestamp = new Date().toISOString().split('T')[0]
  const fitnessLevel = data.userProfile.fitnessLevel.toUpperCase()
  const goal = data.userProfile.goal.replace('-', '_').toUpperCase()
  
  if (format === 'text') {
    const content = exportToText(data)
    const filename = `FitPath_${fitnessLevel}_${goal}_${timestamp}.txt`
    downloadFile(content, filename, 'text/plain')
  } else if (format === 'csv') {
    const content = exportToCSV(data)
    const filename = `FitPath_Progress_${timestamp}.csv`
    downloadFile(content, filename, 'text/csv')
  }
}

export function generatePrintableHTML(data: ExportData): string {
  const { userProfile, routine, completedDays, generatedDate } = data
  
  let html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>FitPath Workout Plan</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          line-height: 1.6;
          margin: 20px;
          color: #333;
        }
        .header {
          text-align: center;
          border-bottom: 3px solid #ff6b35;
          padding-bottom: 20px;
          margin-bottom: 30px;
        }
        .header h1 {
          color: #ff6b35;
          font-size: 2.5em;
          margin: 0;
        }
        .profile {
          background: #f8f9fa;
          padding: 20px;
          border-radius: 8px;
          margin-bottom: 30px;
        }
        .profile h2 {
          color: #2c3e50;
          margin-top: 0;
        }
        .day-section {
          margin-bottom: 30px;
          page-break-inside: avoid;
        }
        .day-header {
          background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
          color: white;
          padding: 15px;
          border-radius: 8px;
          margin-bottom: 15px;
        }
        .day-header h3 {
          margin: 0;
          font-size: 1.5em;
        }
        .exercise {
          background: #fff;
          border: 1px solid #ddd;
          padding: 15px;
          margin-bottom: 10px;
          border-radius: 5px;
        }
        .exercise h4 {
          color: #2c3e50;
          margin: 0 0 10px 0;
        }
        .completed {
          background: #d4edda;
          border-color: #c3e6cb;
        }
        .rest-day {
          background: #fff3cd;
          border-color: #ffeaa7;
        }
        .modification {
          background: #f8d7da;
          border-color: #f5c6cb;
          padding: 10px;
          border-radius: 5px;
          margin-top: 10px;
        }
        .footer {
          text-align: center;
          margin-top: 40px;
          padding-top: 20px;
          border-top: 2px solid #ddd;
          color: #666;
        }
        @media print {
          body { margin: 10px; }
          .day-section { page-break-inside: avoid; }
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>💪 FITPATH WORKOUT PLAN</h1>
        <p>Personalized Fitness Journey</p>
        <p><small>Generated on ${new Date(generatedDate).toLocaleDateString()}</small></p>
      </div>
      
      <div class="profile">
        <h2>📋 Your Profile</h2>
        <p><strong>Fitness Level:</strong> ${userProfile.fitnessLevel.toUpperCase()}</p>
        <p><strong>Goal:</strong> ${userProfile.goal.replace('-', ' ').toUpperCase()}</p>
        <p><strong>Equipment:</strong> ${userProfile.equipment.replace('-', ' ').toUpperCase()}</p>
        <p><strong>Weekly Commitment:</strong> ${userProfile.weeklyDays} days</p>
        <p><strong>Limitations:</strong> ${userProfile.limitations.length > 0 ? userProfile.limitations.join(', ').toUpperCase() : 'NONE'}</p>
        <p><strong>Progress:</strong> ${completedDays.length}/7 days completed (${Math.round((completedDays.length / 7) * 100)}%)</p>
      </div>
  `
  
  routine.forEach((day, index) => {
    const isCompleted = completedDays.includes(index)
    const completedClass = isCompleted ? 'completed' : ''
    
    html += `
      <div class="day-section">
        <div class="day-header">
          <h3>Day ${day.day + 1}: ${day.title} ${isCompleted ? '✅' : ''}</h3>
        </div>
    `
    
    if (day.isRestDay) {
      html += `
        <div class="exercise rest-day">
          <h4>🧘 Rest & Recovery</h4>
          <p>${day.description}</p>
          <p><em>Light stretching or gentle walking is encouraged.</em></p>
        </div>
      `
    } else {
      day.exercises?.forEach((exercise, exIndex) => {
        html += `
          <div class="exercise ${completedClass}">
            <h4>${exIndex + 1}. ${exercise.name}</h4>
            <p><strong>Instructions:</strong> ${exercise.instructions}</p>
            ${exercise.sets ? `<p><strong>Sets:</strong> ${exercise.sets}</p>` : ''}
            ${exercise.duration ? `<p><strong>Duration:</strong> ${exercise.duration}</p>` : ''}
            ${exercise.modification ? `
              <div class="modification">
                <strong>⚠️ Modification:</strong> ${exercise.modification}
              </div>
            ` : ''}
          </div>
        `
      })
    }
    
    html += `</div>`
  })
  
  html += `
      <div class="footer">
        <p><strong>💪 Stay Consistent! Your Fitness Journey Matters!</strong></p>
        <p>Generated by FitPath - Your Personal Fitness Companion</p>
      </div>
    </body>
    </html>
  `
  
  return html
}

export function printWorkoutPlan(data: ExportData) {
  const html = generatePrintableHTML(data)
  const printWindow = window.open('', '_blank')
  if (printWindow) {
    printWindow.document.write(html)
    printWindow.document.close()
    printWindow.focus()
    setTimeout(() => {
      printWindow.print()
      printWindow.close()
    }, 250)
  }
}